apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 267767410086.dkr.ecr.us-east-1.amazonaws.com/monitoring:frontendups
        ports:
        - containerPort: 3001
      imagePullSecrets:
      - name: ecr-credentials

      
      


---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3001
      targetPort: 3001
