apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  
  storageClassName: standard # Set your storage class
  hostPath:
    path: /data/mongodb
