apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard # Set your storage class, should match with the one in PersistentVolume
  resources:
    requests:
      storage: 1Gi
