{
 "title": "Application Metrics / RED Case",
 "description": "Application metrics based on RED Method",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error Rate 4xx",
   "type": "gauge",
   "description": "4xx Error rate on overall requests (1 min)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"^4..$\"}[1m])) /  sum(increase(http_request_duration_ms_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Time taken by system to process incoming requests [1m]",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count[1m])) by (service, route, method, code)  * 60",
     "legendFormat": "{{service}} - {{method}} {{route}} {{code}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes / 1024 /1024) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Response",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{code=~\"2.+\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_requests_total{code=~\"3.+\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_requests_total{code=~\"4.+\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_requests_total{code=~\"5.+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Median Response Time",
   "type": "timeseries",
   "description": "Total sum of RTs ÷ Amount of RTs achieved [1m]",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "95th %ile Response Time",
   "type": "timeseries",
   "description": "Response time slower than 95% of all requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  }
 ]
}